### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by SummerSec** [Marcono1234/codeql-jdk-docker#4]
mkdir database

![image](https://user-images.githubusercontent.com/47944478/130178633-51680d03-06bb-4986-b8ea-ba9f37fe1a70.png)

**Comment by Marcono1234** [comment]
Thanks! I have fixed this in 1179601beb1cec760af906993ad8c8ee8322763f.

The [Docker documentation](https://docs.docker.com/storage/bind-mounts/#differences-between--v-and---mount-behavior) mentions this:
> If you use `--mount` to bind-mount a file or directory that does not yet exist on the Docker host, Docker does not automatically create it for you, but generates an error.

Interestingly this does not seem to be true for Docker Desktop for Windows. For me it creates the directory on the host (i.e. Windows) when it does not exist yet.
